{
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": true,
  "services": [
    "docker"
  ],
  "before_install": [
    "docker build -t myimage -f Dockerfile.dev ."
  ],
  "script": [
    "docker run -e CI=true image npm run test"
  ]
}
